import type { Locale } from "./content";

const en = {
  skip: "Skip to content",
  cta: "Register Now",
  investNow: "Register Now",
  requestMeeting: "Request HCM Meeting",
  viewAgenda: "View Agenda",
  showInterest: "Show interest in this panel",
  downloadBrochure: "Download Brochure",
  checkStatus: "Check status",
  menu: "Menu",
  close: "Close",
  language: "Language",
  nav: {
    home: "Home",
    about: "About",
    why: "Why Attend",
    sectors: "Panel Discussions",
    sessions: "Sessions",
    agenda: "Agenda",
    support: "Registration",
    downloads: "Downloads",
    media: "UGC 2025 Glimpses",
    contact: "Contact Us",
  },
  countdown: {
    label: "Countdown to the summit",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    passed: "The configured summit date has passed. Update the date in the admin panel.",
  },
  footer: {
    summit: "Conclave 2.0",
    help: "Attend",
    legal: "Legal",
    government: "Government",
    privacy: "Privacy Policy",
    terms: "Terms",
    rights: "© 2026 Department of Urban Development And Housing, Government of Madhya Pradesh. All Rights Reserved.",
    socialPending: "Link to be added",
  },
  journeyTitle: "Investor journey",
  form: {
    steps: ["Company", "Contact", "Investment", "Documents"],
    progress: "Form progress",
    step: "Step",
    of: "of",
    back: "Back",
    continue: "Continue",
    save: "Save draft",
    saved: "Draft saved in this browser.",
    submit: "Submit Registration",
    submitting: "Submitting…",
    required: "Required",
    companyName: "Company name",
    orgType: "Type of organisation",
    country: "Country",
    address: "Address",
    city: "City",
    state: "State",
    pin: "PIN",
    website: "Website",
    cin: "CIN or registration number",
    fullName: "Name",
    designation: "Designation",
    email: "Email ID",
    mobile: "Mobile Number",
    sendCode: "Send code",
    code: "One-time code",
    verify: "Verify",
    verified: "Verified",
    devCode: "Email or SMS is not configured, so the code is shown here for local testing only.",
    sectors: "Sector / Interested",
    amount: "Proposed investment amount",
    unit: "Currency",
    inr: "INR crore",
    usd: "USD million",
    district: "Preferred district / region",
    land: "Land required (acres)",
    jobs: "Expected employment",
    timeline: "Project start timeline",
    timelines: {
      "0-6": "Within 6 months",
      "6-12": "6 to 12 months",
      "12-24": "1 to 2 years",
      "24+": "More than 2 years",
    },
    description: "Project description",
    chars: "characters",
    support: "Support needed",
    supportOptions: {
      land: "Land",
      power: "Power",
      approvals: "Approvals",
      incentives: "Incentives",
      other: "Other",
    },
    upload: "Company profile or project report",
    uploadHint: "PDF or DOCX, up to 10 MB. Optional.",
    consent: "I confirm that the information provided is correct.",
    professional: "Professional Information",
    participation: "Participation Preference",
    organization: "Company Name / Organization",
    designationHint: "Enter your designation",
    selectSector: "Select sector",
    selectState: "Select state",
    websiteHint: "Company website (optional)",
    attending: "Attending As",
    selectAttending: "Select your category",
    attendingOptions: {
      investor: "Investor",
      developer: "Developer",
      infrastructure: "Infrastructure Company",
      startup: "Startup",
      association: "Industry Association",
      consultant: "Consultant",
      government: "Government Official",
      academia: "Academia",
      other: "Other",
    },
    states: [
      "Madhya Pradesh",
      "Maharashtra",
      "Delhi NCR",
      "Gujarat",
      "Karnataka",
      "Telangana",
      "Uttar Pradesh",
      "Rajasthan",
      "Tamil Nadu",
      "Other State / UT",
    ],
    sessions: "Select Session",
    sessionsHint: "Select all that you wish to attend",
    plenary: "Plenary Session",
    panel: "Panel",
    hcmTitle: "Honourable Chief Minister One-to-One Meeting Request",
    hcmQuestion: "Would you like to request a meeting with the Hon'ble Chief Minister?",
    yes: "Yes",
    no: "No",
    hcmIfYes: "If yes, please provide the following details",
    hcmOrg: "Organization Name",
    hcmSector: "Investment Sector",
    selectInvestment: "Select investment sector",
    investmentSectors: {
      Public: "Public",
      Private: "Private",
      "State Government": "State Government",
      "Semi Government": "Semi Government",
      "Central Government": "Central Government",
      "Public Sector Undertaking": "Public Sector Undertaking",
      Other: "Other",
    },
    hcmAmount: "Proposed Investment (₹ Crore)",
    hcmLocation: "Proposed Location",
    hcmAgenda: "Brief Meeting Agenda (Maximum 150 Words)",
    words: "words",
    wordLimit: "Maximum 150 words",
    confirmationTitle: "Confirmation",
    confirmInfo: "I confirm that the information provided is correct.",
    updates: "I agree to receive updates via Email and SMS.",
    captcha: "Captcha",
    refresh: "New question",
    org: {
      PRIVATE: "Private",
      PUBLIC: "Public",
      LLP: "LLP",
      STARTUP: "Startup",
      PSU: "PSU",
      FOREIGN: "Foreign entity",
      OTHER: "Other",
    },
  },
  confirmation: {
    title: "Registration submitted",
    body: "Keep this reference number. Submission of the form is not final confirmation. Participation is subject to screening and venue capacity. Selected attendees are contacted by email about three days before the event.",
    localNote: "If email and SMS are not configured on the server, the messages are written to the local outbox instead.",
    reference: "Reference number",
    statusLink: "Check status later",
    another: "Submit another registration",
  },
  status: {
    title: "Check submission status",
    intro: "Enter the reference number and the official email used on the form.",
    reference: "Reference number",
    email: "Official email",
    lookup: "Look up",
    result: "Current status",
  },
  contactForm: {
    name: "Name",
    email: "Email",
    phone: "Phone",
    message: "Message",
    send: "Send message",
    sent: "Your message has been sent to the helpdesk.",
  },
  helpdesk: "Helpdesk",
  phone: "Contact no",
  whatsapp: "WhatsApp",
  dates: "Date",
  venue: "Venue",
  theme: "Theme",
  readMore: "Read more",
  scrollCue: "Scroll to discover",
  backHome: "Back to home",
  notFound: "This page is not on the site.",
};

export type Ui = typeof en;

const hi: Ui = {
  ...en,
  skip: "मुख्य सामग्री पर जाएँ",
  cta: "अभी पंजीकरण करें",
  investNow: "अभी पंजीकरण करें",
  requestMeeting: "मुख्यमंत्री से बैठक का अनुरोध",
  viewAgenda: "कार्यक्रम देखें",
  showInterest: "इस पैनल में रुचि दिखाएँ",
  downloadBrochure: "विवरणिका डाउनलोड करें",
  checkStatus: "स्थिति देखें",
  menu: "मेनू",
  close: "बंद करें",
  language: "भाषा",
  nav: {
    home: "मुखपृष्ठ",
    about: "परिचय",
    why: "क्यों भाग लें",
    sectors: "पैनल चर्चा",
    sessions: "सत्र",
    agenda: "कार्यक्रम",
    support: "पंजीकरण",
    downloads: "डाउनलोड",
    media: "यूजीसी 2025 की झलकियाँ",
    contact: "संपर्क करें",
  },
  countdown: {
    label: "समिट तक उलटी गिनती",
    days: "दिन",
    hours: "घंटे",
    minutes: "मिनट",
    seconds: "सेकंड",
    passed: "निर्धारित समिट तिथि बीत चुकी है। तिथि एडमिन पैनल में बदलें।",
  },
  footer: {
    summit: "कॉन्क्लेव 2.0",
    help: "भागीदारी",
    legal: "विधिक",
    government: "सरकार",
    privacy: "गोपनीयता नीति",
    terms: "शर्तें",
    rights: "© 2026 संचालनालय, नगरीय प्रशासन एवं विकास, मध्य प्रदेश शासन। सर्वाधिकार सुरक्षित।",
    socialPending: "लिंक जोड़ा जाएगा",
  },
  journeyTitle: "निवेशक यात्रा",
  form: {
    ...en.form,
    steps: ["कंपनी", "संपर्क", "निवेश", "दस्तावेज़"],
    progress: "फ़ॉर्म प्रगति",
    step: "चरण",
    of: "में से",
    back: "पीछे",
    continue: "आगे",
    save: "मसौदा सहेजें",
    saved: "मसौदा इस ब्राउज़र में सहेजा गया।",
    submit: "पंजीकरण जमा करें",
    professional: "व्यावसायिक जानकारी",
    participation: "भागीदारी प्राथमिकता",
    organization: "कंपनी / संगठन का नाम",
    designationHint: "अपना पद लिखें",
    selectSector: "क्षेत्र चुनें",
    selectState: "राज्य चुनें",
    websiteHint: "कंपनी की वेबसाइट (वैकल्पिक)",
    attending: "किस रूप में भाग ले रहे हैं",
    selectAttending: "श्रेणी चुनें",
    attendingOptions: {
      investor: "निवेशक",
      developer: "डेवलपर",
      infrastructure: "अवसंरचना कंपनी",
      startup: "स्टार्टअप",
      association: "उद्योग संघ",
      consultant: "सलाहकार",
      government: "सरकारी अधिकारी",
      academia: "शिक्षा जगत",
      other: "अन्य",
    },
    sessions: "सत्र चुनें",
    sessionsHint: "जिन सत्रों में भाग लेना है, वे सभी चुनें",
    plenary: "पूर्ण सत्र",
    panel: "पैनल",
    hcmTitle: "माननीय मुख्यमंत्री से एक-से-एक बैठक का अनुरोध",
    hcmQuestion: "क्या आप माननीय मुख्यमंत्री से बैठक का अनुरोध करना चाहते हैं?",
    yes: "हाँ",
    no: "नहीं",
    hcmIfYes: "यदि हाँ, तो ये विवरण दें",
    hcmOrg: "संगठन का नाम",
    hcmSector: "निवेश क्षेत्र",
    selectInvestment: "निवेश क्षेत्र चुनें",
    investmentSectors: {
      Public: "सार्वजनिक",
      Private: "निजी",
      "State Government": "राज्य सरकार",
      "Semi Government": "अर्ध सरकारी",
      "Central Government": "केंद्र सरकार",
      "Public Sector Undertaking": "सार्वजनिक क्षेत्र का उपक्रम",
      Other: "अन्य",
    },
    hcmAmount: "प्रस्तावित निवेश (₹ करोड़)",
    hcmLocation: "प्रस्तावित स्थान",
    hcmAgenda: "संक्षिप्त बैठक एजेंडा (अधिकतम 150 शब्द)",
    words: "शब्द",
    wordLimit: "अधिकतम 150 शब्द",
    confirmationTitle: "पुष्टि",
    confirmInfo: "मैं पुष्टि करता/करती हूँ कि दी गई जानकारी सही है।",
    updates: "मैं ईमेल और एसएमएस पर अपडेट प्राप्त करने के लिए सहमत हूँ।",
    submitting: "जमा हो रहा है…",
    required: "अनिवार्य",
    companyName: "कंपनी का नाम",
    orgType: "संगठन का प्रकार",
    country: "देश",
    address: "पता",
    city: "शहर",
    state: "राज्य",
    pin: "पिन",
    website: "वेबसाइट",
    cin: "सीआईएन या पंजीकरण संख्या",
    fullName: "नाम",
    designation: "पद",
    email: "ईमेल आईडी",
    mobile: "मोबाइल नंबर",
    sendCode: "कोड भेजें",
    code: "एक बार का कोड",
    verify: "सत्यापित करें",
    verified: "सत्यापित",
    devCode: "ईमेल या एसएमएस सेट नहीं है, इसलिए स्थानीय जाँच के लिए कोड यहाँ दिख रहा है।",
    sectors: "क्षेत्र / रुचि",
    amount: "प्रस्तावित निवेश राशि",
    unit: "मुद्रा",
    inr: "INR करोड़",
    usd: "USD मिलियन",
    district: "पसंदीदा ज़िला / क्षेत्र",
    land: "आवश्यक भूमि (एकड़)",
    jobs: "अपेक्षित रोज़गार",
    timeline: "परियोजना आरंभ की समय-सीमा",
    timelines: {
      "0-6": "6 माह के भीतर",
      "6-12": "6 से 12 माह",
      "12-24": "1 से 2 वर्ष",
      "24+": "2 वर्ष से अधिक",
    },
    description: "परियोजना विवरण",
    chars: "अक्षर",
    support: "आवश्यक सहयोग",
    supportOptions: {
      land: "भूमि",
      power: "बिजली",
      approvals: "अनुमोदन",
      incentives: "प्रोत्साहन",
      other: "अन्य",
    },
    upload: "कंपनी प्रोफ़ाइल या परियोजना रिपोर्ट",
    uploadHint: "पीडीएफ या डीओसीएक्स, अधिकतम 10 एमबी। वैकल्पिक।",
    consent: "मैं पुष्टि करता/करती हूँ कि विवरण सही हैं और मैंने गोपनीयता नीति पढ़ ली है।",
    captcha: "कैप्चा",
    refresh: "नया प्रश्न",
    org: en.form.org,
  },
  confirmation: {
    title: "पंजीकरण जमा हो गया",
    body: "यह संदर्भ संख्या रखें। फॉर्म जमा करना अंतिम पुष्टि नहीं है। भागीदारी जाँच और स्थल क्षमता पर निर्भर है। चयनित प्रतिभागियों को कार्यक्रम से लगभग तीन दिन पहले ईमेल पर सूचना दी जाती है।",
    localNote: "यदि सर्वर पर ईमेल और एसएमएस सेट नहीं हैं, तो संदेश स्थानीय आउटबॉक्स में लिखे जाते हैं।",
    reference: "संदर्भ संख्या",
    statusLink: "बाद में स्थिति देखें",
    another: "एक और पंजीकरण जमा करें",
  },
  status: {
    title: "आवेदन की स्थिति",
    intro: "संदर्भ संख्या और फ़ॉर्म पर दिया आधिकारिक ईमेल दर्ज करें।",
    reference: "संदर्भ संख्या",
    email: "आधिकारिक ईमेल",
    lookup: "देखें",
    result: "वर्तमान स्थिति",
  },
  contactForm: {
    name: "नाम",
    email: "ईमेल",
    phone: "फ़ोन",
    message: "संदेश",
    send: "संदेश भेजें",
    sent: "आपका संदेश हेल्पडेस्क को भेज दिया गया है।",
  },
  helpdesk: "हेल्पडेस्क",
  phone: "संपर्क नंबर",
  whatsapp: "व्हाट्सऐप",
  dates: "तिथि",
  venue: "स्थल",
  theme: "विषय",
  readMore: "और पढ़ें",
  scrollCue: "आगे स्क्रॉल करें",
  backHome: "मुखपृष्ठ पर जाएँ",
  notFound: "यह पृष्ठ साइट पर नहीं है।",
};

export function getUi(locale: Locale): Ui {
  return locale === "hi" ? hi : en;
}
