import type { Locale } from "./content";

const en = {
  skip: "Skip to content",
  cta: "Submit Investment Interest",
  investNow: "Invest Now",
  downloadBrochure: "Download Brochure",
  checkStatus: "Check status",
  menu: "Menu",
  close: "Close",
  language: "Language",
  nav: {
    home: "Home",
    about: "About the Summit",
    why: "Why Invest in MP",
    sectors: "Sectors",
    agenda: "Agenda and Events",
    support: "Investor Support",
    downloads: "Downloads",
    media: "Media",
    contact: "Contact",
  },
  countdown: {
    label: "Countdown to the summit",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    passed: "The configured summit date has passed. Update the date in the admin panel.",
  },
  footer: {
    summit: "Summit",
    help: "Investors",
    legal: "Legal",
    government: "Government",
    privacy: "Privacy Policy",
    terms: "Terms",
    rights: "Madhya Pradesh Global Investors Summit. Page content is managed by the organising team.",
    socialPending: "Link to be added",
  },
  journeyTitle: "Investor journey",
  form: {
    steps: ["Company", "Contact", "Investment", "Documents"],
    progress: "Form progress",
    step: "Step",
    of: "of",
    back: "Back",
    continue: "Continue",
    save: "Save draft",
    saved: "Draft saved in this browser.",
    submit: "Submit interest",
    submitting: "Submitting…",
    required: "Required",
    companyName: "Company name",
    orgType: "Type of organisation",
    country: "Country",
    address: "Address",
    city: "City",
    state: "State",
    pin: "PIN",
    website: "Website",
    cin: "CIN or registration number",
    fullName: "Full name",
    designation: "Designation",
    email: "Official email",
    mobile: "Mobile / WhatsApp",
    sendCode: "Send code",
    code: "One-time code",
    verify: "Verify",
    verified: "Verified",
    devCode: "Email or SMS is not configured, so the code is shown here for local testing only.",
    sectors: "Sector",
    amount: "Proposed investment amount",
    unit: "Currency",
    inr: "INR crore",
    usd: "USD million",
    district: "Preferred district / region",
    land: "Land required (acres)",
    jobs: "Expected employment",
    timeline: "Project start timeline",
    timelines: {
      "0-6": "Within 6 months",
      "6-12": "6 to 12 months",
      "12-24": "1 to 2 years",
      "24+": "More than 2 years",
    },
    description: "Project description",
    chars: "characters",
    support: "Support needed",
    supportOptions: {
      land: "Land",
      power: "Power",
      approvals: "Approvals",
      incentives: "Incentives",
      other: "Other",
    },
    upload: "Company profile or project report",
    uploadHint: "PDF or DOCX, up to 10 MB. Optional.",
    consent: "I confirm that the details are correct and I have read the privacy policy.",
    captcha: "Captcha",
    refresh: "New question",
    org: {
      PRIVATE: "Private",
      PUBLIC: "Public",
      LLP: "LLP",
      STARTUP: "Startup",
      PSU: "PSU",
      FOREIGN: "Foreign entity",
      OTHER: "Other",
    },
  },
  confirmation: {
    title: "Interest received",
    body: "Keep this reference number. A confirmation is sent to the email and mobile number you verified.",
    localNote: "If email and SMS are not configured on the server, the messages are written to the local outbox instead.",
    reference: "Reference number",
    statusLink: "Check status later",
    another: "Submit another interest",
  },
  status: {
    title: "Check submission status",
    intro: "Enter the reference number and the official email used on the form.",
    reference: "Reference number",
    email: "Official email",
    lookup: "Look up",
    result: "Current status",
  },
  contactForm: {
    name: "Name",
    email: "Email",
    phone: "Phone",
    message: "Message",
    send: "Send message",
    sent: "Your message has been sent to the helpdesk.",
  },
  helpdesk: "Helpdesk",
  phone: "Phone",
  whatsapp: "WhatsApp",
  dates: "Dates",
  venue: "Venue",
  theme: "Theme",
  readMore: "Read more",
  backHome: "Back to home",
  notFound: "This page is not on the site.",
};

export type Ui = typeof en;

const hi: Ui = {
  ...en,
  skip: "मुख्य सामग्री पर जाएँ",
  cta: "निवेश रुचि जमा करें",
  investNow: "अभी निवेश करें",
  downloadBrochure: "विवरणिका डाउनलोड करें",
  checkStatus: "स्थिति देखें",
  menu: "मेनू",
  close: "बंद करें",
  language: "भाषा",
  nav: {
    home: "मुखपृष्ठ",
    about: "समिट के बारे में",
    why: "एमपी में निवेश क्यों",
    sectors: "क्षेत्र",
    agenda: "कार्यक्रम और आयोजन",
    support: "निवेशक सहायता",
    downloads: "डाउनलोड",
    media: "मीडिया",
    contact: "संपर्क",
  },
  countdown: {
    label: "समिट तक उलटी गिनती",
    days: "दिन",
    hours: "घंटे",
    minutes: "मिनट",
    seconds: "सेकंड",
    passed: "निर्धारित समिट तिथि बीत चुकी है। तिथि एडमिन पैनल में बदलें।",
  },
  footer: {
    summit: "समिट",
    help: "निवेशक",
    legal: "विधिक",
    government: "सरकार",
    privacy: "गोपनीयता नीति",
    terms: "शर्तें",
    rights: "मध्य प्रदेश ग्लोबल इन्वेस्टर्स समिट। पृष्ठ की सामग्री आयोजन टीम प्रबंधित करती है।",
    socialPending: "लिंक जोड़ा जाएगा",
  },
  journeyTitle: "निवेशक यात्रा",
  form: {
    ...en.form,
    steps: ["कंपनी", "संपर्क", "निवेश", "दस्तावेज़"],
    progress: "फ़ॉर्म प्रगति",
    step: "चरण",
    of: "में से",
    back: "पीछे",
    continue: "आगे",
    save: "मसौदा सहेजें",
    saved: "मसौदा इस ब्राउज़र में सहेजा गया।",
    submit: "रुचि जमा करें",
    submitting: "जमा हो रहा है…",
    required: "अनिवार्य",
    companyName: "कंपनी का नाम",
    orgType: "संगठन का प्रकार",
    country: "देश",
    address: "पता",
    city: "शहर",
    state: "राज्य",
    pin: "पिन",
    website: "वेबसाइट",
    cin: "सीआईएन या पंजीकरण संख्या",
    fullName: "पूरा नाम",
    designation: "पद",
    email: "आधिकारिक ईमेल",
    mobile: "मोबाइल / व्हाट्सऐप",
    sendCode: "कोड भेजें",
    code: "एक बार का कोड",
    verify: "सत्यापित करें",
    verified: "सत्यापित",
    devCode: "ईमेल या एसएमएस सेट नहीं है, इसलिए स्थानीय जाँच के लिए कोड यहाँ दिख रहा है।",
    sectors: "क्षेत्र",
    amount: "प्रस्तावित निवेश राशि",
    unit: "मुद्रा",
    inr: "INR करोड़",
    usd: "USD मिलियन",
    district: "पसंदीदा ज़िला / क्षेत्र",
    land: "आवश्यक भूमि (एकड़)",
    jobs: "अपेक्षित रोज़गार",
    timeline: "परियोजना आरंभ की समय-सीमा",
    timelines: {
      "0-6": "6 माह के भीतर",
      "6-12": "6 से 12 माह",
      "12-24": "1 से 2 वर्ष",
      "24+": "2 वर्ष से अधिक",
    },
    description: "परियोजना विवरण",
    chars: "अक्षर",
    support: "आवश्यक सहयोग",
    supportOptions: {
      land: "भूमि",
      power: "बिजली",
      approvals: "अनुमोदन",
      incentives: "प्रोत्साहन",
      other: "अन्य",
    },
    upload: "कंपनी प्रोफ़ाइल या परियोजना रिपोर्ट",
    uploadHint: "पीडीएफ या डीओसीएक्स, अधिकतम 10 एमबी। वैकल्पिक।",
    consent: "मैं पुष्टि करता/करती हूँ कि विवरण सही हैं और मैंने गोपनीयता नीति पढ़ ली है।",
    captcha: "कैप्चा",
    refresh: "नया प्रश्न",
    org: en.form.org,
  },
  confirmation: {
    title: "रुचि प्राप्त हुई",
    body: "यह संदर्भ संख्या रखें। पुष्टि आपके सत्यापित ईमेल और मोबाइल पर भेजी जाती है।",
    localNote: "यदि सर्वर पर ईमेल और एसएमएस सेट नहीं हैं, तो संदेश स्थानीय आउटबॉक्स में लिखे जाते हैं।",
    reference: "संदर्भ संख्या",
    statusLink: "बाद में स्थिति देखें",
    another: "एक और रुचि जमा करें",
  },
  status: {
    title: "आवेदन की स्थिति",
    intro: "संदर्भ संख्या और फ़ॉर्म पर दिया आधिकारिक ईमेल दर्ज करें।",
    reference: "संदर्भ संख्या",
    email: "आधिकारिक ईमेल",
    lookup: "देखें",
    result: "वर्तमान स्थिति",
  },
  contactForm: {
    name: "नाम",
    email: "ईमेल",
    phone: "फ़ोन",
    message: "संदेश",
    send: "संदेश भेजें",
    sent: "आपका संदेश हेल्पडेस्क को भेज दिया गया है।",
  },
  helpdesk: "हेल्पडेस्क",
  phone: "फ़ोन",
  whatsapp: "व्हाट्सऐप",
  dates: "तिथियाँ",
  venue: "स्थल",
  theme: "विषय",
  readMore: "और पढ़ें",
  backHome: "मुखपृष्ठ पर जाएँ",
  notFound: "यह पृष्ठ साइट पर नहीं है।",
};

export function getUi(locale: Locale): Ui {
  return locale === "hi" ? hi : en;
}
